version: "3"

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: >
      sh -c "python manage.py collectstatic && python manage.py makemigrations vendor && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=vendor_dev_db
      - DB_USER=dev@vendor
      - DB_PASS=dev@vendor
    depends_on:
      - db

  test_app:
    build:
      context: .
    volumes:
      - .:/app
    command: >
      sh -c "pytest"
    environment:
      - DB_HOST=db
      - DB_NAME=vendor_dev_db
      - DB_USER=dev@vendor
      - DB_PASS=dev@vendor
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=vendor_dev_db
      - POSTGRES_USER=dev@vendor
      - POSTGRES_PASSWORD=dev@vendor
    ports:
      - "5432:5432"
    volumes:
    - vendor_project_db_volume:/var/lib/postgresql/data

volumes:
  vendor_project_db_volume:
